name: Build and Push Docker Image

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          cd frontend
          docker build -t ghcr.io/${{ github.repository }}:latest .

      # Step 4: Push the Docker image to GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
